name: Ads API test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Dependencies
        run: pip install requests
      - name: Testcall Ads API
        env:
          ADS_CLIENT_ID: ${{ secrets.ADS_CLIENT_ID }}
          ADS_CLIENT_SECRET: ${{ secrets.ADS_CLIENT_SECRET }}
          ADS_REFRESH_TOKEN: ${{ secrets.ADS_REFRESH_TOKEN }}
          ADS_PROFILE_ID: ${{ secrets.ADS_PROFILE_ID }}
        run: python ads_api_test.py
